### ISSUE TITLE
log_channel::end_session()が同時に呼ばれると、datastore::update_min_epoch_id()で無限ループにおちいる可能性がある。

### ISSUE THREAD

**Issue by umegane** [project-tsurugi/limestone#60]
log_channel::end_session()から呼ばれる、datastore::update_min_epoch_id()で次の処理が存在する。

```
auto old_epoch_id = epoch_id_recorded_.load();
while (true) {
    if (old_epoch_id >= to_be_epoch) {
        break;
    }
    if (epoch_id_recorded_.compare_exchange_strong(old_epoch_id, to_be_epoch)) {
        std::lock_guard<std::mutex> lock(mtx_epoch_file_);

        FILE* strm = fopen(epoch_file_path_.c_str(), "a");  // NOLINT(*-owning-memory)
        if (!strm) {
            LOG_AND_THROW_IO_EXCEPTION("fopen failed", errno);
        }
        log_entry::durable_epoch(strm, static_cast<epoch_id_type>(epoch_id_recorded_.load()));
        if (fflush(strm) != 0) {
            LOG_AND_THROW_IO_EXCEPTION("fflush failed", errno);
        }
        if (fsync(fileno(strm)) != 0) {
            LOG_AND_THROW_IO_EXCEPTION("fsync failed", errno);
        }
        if (fclose(strm) != 0) {  // NOLINT(*-owning-memory)
            LOG_AND_THROW_IO_EXCEPTION("fclose failed", errno);
        }
        break;
    }
}
```
この処理を複数スレッドど同時に処理したとき`epoch_id_recorded_.compare_exchange_strong(old_epoch_id, to_be_epoch)`
の部分でepoch_id_recorded_の更新に失敗したスレッドは無限ループにおちいる。

要修正だが、どう修正すべきか分からない。

**Comment by umegane** [comment]
> epoch_id_recorded_の更新に失敗したらold_epoch_idの値が書き換わるので、if (old_epoch_id >= to_be_epoch) が成立し、loopから抜けるというつもりです。何か勘違いしたでしょうか？

@t-horikawa 
old_epoch_id はwhileループの外で設定しているので、ループに入った瞬間に old_epoch_id < to_be_epoch だと、
epoch_id_recorded_.compare_exchange_strong(old_epoch_id, to_be_epoch)が成功するまでループから
抜けられません。複数のスレッド同じold_epoch_idでループに入ると、epoch_id_recorded_.compare_exchange_strong(old_epoch_id, to_be_epoch)が成功するスレッドは一つだけなので、他のスレッドは、ループから抜けることができなくなりませんか。

**Comment by umegane** [comment]
このコードにも同じ問題がありそう。
```
to_be_epoch = upper_limit;
old_epoch_id = epoch_id_informed_.load();
while (true) {
    if (old_epoch_id >= to_be_epoch) {
        break;
    }
    if (epoch_id_informed_.compare_exchange_strong(old_epoch_id, to_be_epoch)) {
        if (persistent_callback_) {
            persistent_callback_(to_be_epoch);
        }
        break;
    }
}
```

**Comment by t-horikawa** [comment]
https://cpprefjp.github.io/reference/atomic/atomic/compare_exchange_strong.html

`そうでなければ failure メモリオーダーで expected を現在の値で置き換える`

**Comment by umegane** [comment]
私のcompare_exchange_strong()の理解が間違っているということですね。
仕様を確認します。

**Comment by umegane** [comment]
@t-horikawa 
私のcompare_exchange_strong()の理解が間違っていて、無限ループにはならないことを
理解しました。

ところで、log_channel::end_session()が同時に呼ばれ、to_be_epochの値が異なる
値になるケースで、エポックファイルに記録されるepoch_idが昇順に並ばなかったり、
epoch_id_recorded_の値と、エポックファイルの最後に書かれているepch_idの
値が一致しない可能性があると思うのですが、この可能性もどこかで排除していますか。

to_be_epochの値が異なる値にならないので問題ないのかもと思っているのですが、
コードを追いきれていません。

**Comment by umegane** [comment]
このIssueは私の誤認だったのでクローズします。

> ところで、log_channel::end_session()が同時に呼ばれ、to_be_epochの値が異なる
値になるケースで、エポックファイルに記録されるepoch_idが昇順に並ばなかったり、
epoch_id_recorded_の値と、エポックファイルの最後に書かれているepch_idの
値が一致しない可能性があると思うのですが、この可能性もどこかで排除していますか。
あるいは、そうなっても問題ないという設計でしょうか。

この件は本Issueとは別件なので、別途検討の上、必要と判断したらIssue化します。

**Comment by t-horikawa** [comment]
https://github.com/project-tsurugi/limestone/issues/60#issuecomment-2461924630
```
to_be_epochの値が異なる値になるケースで、
1) エポックファイルに記録されるepoch_idが昇順に並ばなかったり、
2) epoch_id_recorded_の値と、エポックファイルの最後に書かれているepch_idの値が一致しない
```
https://github.com/project-tsurugi/limestone/blob/3398b45eb776fd09271f329f3844656c822fcad4/src/limestone/datastore.cpp#L178-L202
の部分だと思います。そこは、1), 2)の状況にならないようにコーディングしたつもりです。
複数スレッドの動作順により1), 2)が発生するのであれば、その動作順を具体的に示して頂ければありがたいです。

なお、2)について、to_be_epochがepoch_id_recorded_より小さい場合は、ある意味「エポックファイルの最後に書かれているepch_idの値が一致しない（to_be_epochよりも大きな値が既に書かれているため、その値を書く必要はない）」となりますが、それは問題ないはずです。

**Comment by t-horikawa** [comment]
よくよく考えたら、
https://github.com/project-tsurugi/limestone/blob/3398b45eb776fd09271f329f3844656c822fcad4/src/limestone/datastore.cpp#L184
を実行する前はまだクリティカルセクションに入っていないので、例えば、to_be_epochが10と11のスレッドがその順で
https://github.com/project-tsurugi/limestone/blob/3398b45eb776fd09271f329f3844656c822fcad4/src/limestone/datastore.cpp#L183
のcompare_exchange_strongを通過した後、
https://github.com/project-tsurugi/limestone/blob/3398b45eb776fd09271f329f3844656c822fcad4/src/limestone/datastore.cpp#L184
のlock獲得は11, 10の順になるというケースはあり得ます。そうなるとepochファイルへの書き込みは逆順（epochファイル上で11から戻る形となる）となり、例で示したケースだと11から戻る形となる10のepoch書き込みは無視する必要がありました。その場合でも、他の問題はないです（10を書き込んだ時点で11までdurableになっている）。

epochファイルでの逆順を避けるためには、184と186の間に、if (to_be_epoch < epoch_id_recorded_.load()) { break; } を入れれば良いです。このとき、もしto_be_epochが12のスレッドが来ていてepoch_id_recorded_を12に更新していたとしても、直ぐに12のスレッドがepochファイルに12を書き込むことになるので、これもそれほどの問題にはなりません。そして、そのような連鎖は無限には続きません（現実には10, 11の連鎖すらないはず）ので、compare_exchange_strongで競合した後、間髪を入れずに最大のto_be_epochの値がファイルに書き込まれることになります。
