### ISSUE TITLE
Epochファイルに書き込むEpoch IDとpersistent_callback_に渡されるEpoc IDが一致しないことがある。

### ISSUE THREAD

**Issue by umegane** [project-tsurugi/limestone#63]
同一のEpochファイルに書き込むEpoch IDとpersistent_callback_に渡されるEpoc IDが一致しないことがある。
これは、Epochファイルの書き込みと、persistent_callback_の呼び出しで、epoch_idの決定ロジックが
異なるのが原因である。

```
// epochファイルの更新
auto to_be_epoch = upper_limit;
if (from_switch_epoch && (to_be_epoch > static_cast<std::uint64_t>(max_finished_epoch))) {
    to_be_epoch = static_cast<std::uint64_t>(max_finished_epoch);
}

// persistent_callback_の呼び出し
to_be_epoch = upper_limit;
```

例えば、Epoch ID = 3 のEpochのEpochファイルの書き込み/persistent_callback_を行う直前に、
switch_epochが呼ばれると、　upper_limit = 4, max_finished_epoch = 3 となるケースが
ありえる。これが起きるのは、Epoch ID = 4で、ログの書き込みが行われなかったときなので、
あまり問題はないかもしれないが、永続化したEpoch IDより大きなEpoch IDが、
persistent_callback_に渡され気持ち悪い。

防御的な意味で、どちらも同じロジックにすべき。

**Comment by umegane** [comment]
datastore::update_min_epoch_id の該当箇所を変更しました。

persistent_callback_に渡すEpoch IDを、Epochファイルに出力する
Epoch IDと同じ値になるようにロジックを修正しました。

**Comment by umegane** [comment]
この修正を入れると、UTが通らなくなったのでReopenします。

[persistent_callback_にセットするEpock IDを決める処理](https://github.com/project-tsurugi/limestone/blob/master/src/limestone/datastore.cpp#L205)を[Epochファイルに書き込むEpochを決めている処理](https://github.com/project-tsurugi/limestone/blob/master/src/limestone/datastore.cpp#L174-L177)と
同内容に書き換えたところUTが通らなくなる(無限ループに陥る)ようになりました。

現状の実装では、switch_epochが呼ばれswitch_epochの前のepochでPWALが一切書かれていない場合、
Epochファイルは更新されませんが、persistent_callback_は呼ばれます(※)。
この修正により、PWALがかかれないEpochに対して、persistent_callback_を呼ばなくなるため、
[UT](https://github.com/project-tsurugi/limestone/blob/master/test/limestone/api/datastore_test.cpp#L112-L122)
が無限ループに陥ります。

※ 厳密にはPWALを一切書かなくても、log_channelのセッションをbegin -> end するだけで、epochが更新される

@t-horikawa このテストは、persistent_callback_が呼ばれることのテストなので、上記コードの修正に
合わせてpersistent_callback_が呼ばれるように、log_channelでセッションの開始、終了するコードを
入れれば良いと思っています。PWALの更新がなくても、persistent_callback_を呼ぶ現行の
仕様を維持すべきであれば、その旨をコメント願います。

**Comment by t-horikawa** [comment]
「PWALの更新がなくても、persistent_callback_を呼ぶ現行の仕様を維持すべき」でした。
limestone UTの中には田辺さんが作成されたものがあります。それは、「shirakamiはlimestoneがこのように動作することを前提にしている」というものなので、それが通らないとshirakamiが正しく動かないことになります。そのようなUTは修正NGです。
「PWALの更新がなくても、persistent_callback_を呼ぶ」は「shirakamiはlimestoneがこのように動作することを前提」の一つだったと記憶しています。

**Comment by umegane** [comment]
@t-horikawa UTが通らないのであれば、明らかにUTにバグがあると思われる状況を除き、現状の仕様を維持すべきということですね。
了解です。

このIssueの問題である、Epochファイルに書き込むEpoch IDとPesitance Callbackに渡されるEpoch IDが一致せず、
Persitance Callbackに渡されるEpoch IDの方が大きくなることの是非については別問題なので、IssueはOpenにした
ままにします。

**Comment by t-horikawa** [comment]
limestoneは図の通りに動作するように作成しました。log書き込みのない(1)の場合は、Epochファイルへの書き込みは行わず（Epochファイルに記録されているEpoch IDは前回書き込まれた値のまま）、Pesitance Callbackに渡すEpoch IDだけが進んでいきます。
![Image](https://github.com/user-attachments/assets/4ccee714-13b5-4f8f-8f74-1aae3fe75591)

「このIssueの問題」が「不正な動作となる可能性がある」を意味しているのであれば、上記の設計に問題があるということになります。

**Comment by t-horikawa** [comment]
https://github.com/project-tsurugi/limestone/issues/63#issuecomment-2475305753
においてNGなのはpersistent_callback_(n)の後からlog_channelがepoch nのsessionを開始すること（図の動作）です。
![Image](https://github.com/user-attachments/assets/5cfbb540-6224-4d99-a3eb-096294734fec)

そして、初期に質問を受けた
https://github.com/project-tsurugi/limestone/blob/3398b45eb776fd09271f329f3844656c822fcad4/src/limestone/log_channel.cpp#L44-L48
でチェックを行っている意味はこれでした（忘却の彼方でした、すいません）。

**Comment by umegane** [comment]
> でチェックを行っている意味はこれ（read after writeパターンの活用）でした。忘却の彼方でした、すいません。

ようやく理解できました。

log_channel::begin_session()のスレッドをL, datastore::switch_epochをDと表示します。

1. L: epoch_id_switched_.load()  => 10
2: D: epoch_id_switched_.store(11))
3. D: current_epoch_id_.load() => UINT64_MAX
4. L: current_epoch_id_.store(10)

という順序で処理が行われたときに、Epoch ID=10のセッションがあるにも
かかわらず、スレッドDはそれを検知できずに、Epoch ID = 10 のpersistent_callback
を呼んでしまうということですね。

1と2が入れ替わると、Epoch ID=11のセッションが始まり、Epoch ID= 10のpersistent_callback
が呼ばれるので問題なし、3, 4が入れ替わると、スレッドDはEpoch ID=10のセッションを検知し
Epoch ID=10 persistent_callbackを呼ばないので問題なし

そこで、4.の処理の後に、epoch_id_switched_.load()を実行すれば、このシーケンスで
処理が実行されて不整合状態になっているのが検知できる。この競合が連続して起きる
可能性が0ではないので、競合がおきていない状態になるまでループする必要があると。

std::atomic_thread_fence(std::memory_order_acq_rel);が必要な理由だけがわかりませんでした。

**Comment by umegane** [comment]
> 「このIssueの問題」が「不正な動作となる可能性がある」を意味しているのであれば、上記の設計に問題があるということになります。

persistent_callback_という名称なのに、永続化していないEpochのEpoch IDを通知するのは直感に反するので、本当に
これで良いのかと思っただけです。完全に意図した設計であれば、問題ありません。

**Comment by umegane** [comment]
これは、仕様通りということでクローズします。

**Comment by t-horikawa** [comment]
「永続化していないEpoch」という表現は誤解を生みそう。
「永続化すべきデータ（"PWAL" とか "DB書き込み" という方が良いか？）のないEpoch」ですね。要は「永続化（操作）不要Epoch」。
