### ISSUE TITLE
特定の条件下でepoch_idが18446744073709551614になる。

### ISSUE THREAD

**Issue by umegane** [project-tsurugi/limestone#64]
`datastore::update_min_epoch_id()`で、設定される、`epoch_id_recorded_`, `epoch_id_informed_`
の値、およびEpochファイルに書き込まれるEpoch ID, persistent_callback_で通知されるEpoch IDが
特定の条件下で18446744073709551614, または18446744073709551615になる。

#### 条件1  epoch_id_switched_ == 0 

`epoch_id_switched_`のときに、下のコードで`upper_limit`

```
    auto upper_limit = epoch_id_switched_.load() - 1;
```

で`upper_limit`がUINT64_MAXになる。

#### 条件2 アクティブなログチャネルが存在しない

下のコードによりupper_limitが更新されるが、アクティブなログチャネルが存在しないと、
`e->current_epoch_id_` の値は全てUINT64_MAXなので、`upper_limit`がUINT64_MAX - 1
(=18446744073709551614)になる。ログチャネルが一つも存在しない場合は、
`upper_limit`がUINT64_MAX(=18446744073709551615)になる。

```
    for (const auto& e : log_channels_) {
        auto working_epoch = static_cast<epoch_id_type>(e->current_epoch_id_.load());
        if ((working_epoch - 1) < upper_limit) {
            upper_limit = working_epoch - 1;
        }
```

epoch_id_switched_ = 0 のときに特別な処理を入れるか、epoch_idの初期値を0でなく1にする必要がある。
また、条件2で示したたコードで、`current_epoch_id_`がUINT64_MAXの場合を特別扱いしていないことが
問題ないのかも検討が必要。

**Comment by umegane** [comment]
次のように対応しました。

epoch_id_switched_ == 0 の場合、Epochファイルの更新も、Pesistance Callbackの呼び出しも不要なので、
datastore::update_min_epoch_id()の処理をスキップするように修正

```cpp
//修正前
void datastore::update_min_epoch_id(bool from_switch_epoch) {  // NOLINT(readability-function-cognitive-complexity)
    auto upper_limit = epoch_id_switched_.load() - 1;

//修正後
void datastore::update_min_epoch_id(bool from_switch_epoch) {  // NOLINT(readability-function-cognitive-complexity)
    auto upper_limit = epoch_id_switched_.load();
    if (upper_limit == 0) {
        return; // If epoch_id_switched_ is zero, it means no epoch has been switched, so updating epoch_id_recorded_ and epoch_id_informed_ is unnecessary.
    }
    upper_limit--;
```

current_epoch_id_ == UINT64_MAX は、当該ログチャネルがインアクティブであることを
示すので、uppper_limitにcurrent_epoch_id_ - 1 をセットしないようにする。


```cpp
//修正前
for (const auto& e : log_channels_) {
    auto working_epoch = static_cast<epoch_id_type>(e->current_epoch_id_.load());
    if ((working_epoch - 1) < upper_limit) {
        upper_limit = working_epoch - 1;
    }
    auto finished_epoch = e->finished_epoch_id_.load();
    if (max_finished_epoch < finished_epoch) {
        max_finished_epoch = finished_epoch;
    }
}

//修正後
for (const auto& e : log_channels_) {
    auto working_epoch = static_cast<epoch_id_type>(e->current_epoch_id_.load());
    if ((working_epoch - 1) < upper_limit && working_epoch != UINT64_MAX) {
        upper_limit = working_epoch - 1;
    }
    auto finished_epoch = e->finished_epoch_id_.load();
    if (max_finished_epoch < finished_epoch) {
        max_finished_epoch = finished_epoch;
    }
}
```

**Comment by t-horikawa** [comment]
https://github.com/project-tsurugi/limestone/issues/64#issue-2655404485
```
下のコードによりupper_limitが更新されるが、アクティブなログチャネルが存在しないと、
e->current_epoch_id_ の値は全てUINT64_MAXなので、upper_limitがUINT64_MAX - 1
(=18446744073709551614)になる。
```
になりますか？
epoch_id_switched_.load()が0のときにアンダーフローするケースは見過ごしてしまいましたが、それが修正された後では、「アクティブなログチャネルが存在しない」場合、
```
if ((working_epoch - 1) < upper_limit) {
```
のifが成立しないのでupper_limit（初期値として"epoch_id_switched_.load() - 1"が入っている）は更新されないはず（という意図でこの部分作成しました）。

**Comment by umegane** [comment]
@t-horikawa アンダーフローがおきなければ、upper_limitがUINT64_MAX - 1にならないというのは、
そのとおりです。ですので、`working_epoch != UINT64_MAX` のコードはなくても動作に支障は
ありません。

将来のメンテナンスで仕様変更をしたときに、
```
if ((working_epoch - 1) < upper_limit) {
```

この条件式が、セッションが非アクティブであることの判断を兼ねていることを
見落とさないように、`working_epoch != UINT64_MAX` の上家を追加しました。
それによる、コストの上昇は、許容できると思います。

高変更しないと正しく動作しないというわけではないです。

**Comment by t-horikawa** [comment]
「それによる、コストの上昇、許容できる」 → そうですね。
前職の世界観（１クロックサイクルたりとも無駄を許容しない）がついつい顔を出してしまう。

**Comment by umegane** [comment]
対応完了したのでクローズします。
