### ISSUE TITLE
エポックファイルの更新前にpersistance_callbackを 呼んでしまう

### ISSUE THREAD

**Issue by umegane** [project-tsurugi/limestone#67]
limestoneにエポックファイルの更新前にpersistance_callbackを
呼んでしまうバグがある。例えば次のようなケース。

1. max_finished_epochが3のとき、2つのスレッドが同時にdatastore::update_min_epoch_id()を呼び出す。
2. [このforループ](https://github.com/project-tsurugi/limestone/blob/wip/log-0.7/src/limestone/datastore.cpp#L179-L188)で、どちらのスレッドもupper_limitが4になる。
3. スレッド1の処理が、[ここまで](https://github.com/project-tsurugi/limestone/blob/wip/log-0.7/src/limestone/datastore.cpp#L201)まで進み、max_finished_epochが4になる。この時点で、スレッド2の処理は、[ここまで](https://github.com/project-tsurugi/limestone/blob/wip/log-0.7/src/limestone/datastore.cpp#L195)より前までしか達していない。
4. その後、スレッド1が、エポックファイルを書き終わる前に、スレッド2の処理が進んでいく。
5. [この処理](https://github.com/project-tsurugi/limestone/blob/wip/log-0.7/src/limestone/datastore.cpp#L195-L199)で、old_epoch_id が4になり、whileの直後のif文が真になり、スレッド2はループから抜ける。
6. スレッド2は、そのままepoch_id = 4 でpersistent_callback_を呼び出し、epoch_id_informed_が4になる。
7. その後、スレッド1の処理がすすみ、EpochファイルにEpoch ID = 4が書き込まれる。

別スレッドがepoch更新を進めてくれていることを検出したときに実行される

https://github.com/project-tsurugi/limestone/blob/003f01a150b29ebb7df19c7b408638a678ce3eb6/src/limestone/datastore.cpp#L198

はbreak;ではなく、return;とすべき。

**Comment by t-horikawa** [comment]
「break;ではなく、return;とすべき。」は間違いで、
https://github.com/project-tsurugi/limestone/commit/77552d6dc3208bbe9c7d39de0bab37f96f926329
とするのが正しい。

**Comment by umegane** [comment]
tsrugi-issuers の[Issue #1034](https://github.com/project-tsurugi/tsurugi-issues/issues/1034)で対応済みなのでクローズします。
